In [47]:
import pandas as pd
import numpy as np

In [48]:
pd.__version__

'3.0.5'

In [49]:
df = pd.read_csv('../data/car_fuel_efficiency_2026.csv')

In [50]:
df.shape

(10000, 11)

In [98]:
df.head(3)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5


In [52]:
df.fuel_type.nunique()

3

In [53]:
df['fuel_type'].nunique()

3

In [54]:
(df.isnull().sum() > 0).sum()

np.int64(2)

In [55]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [56]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [57]:
df.horsepower.median()

np.float64(254.0)

In [58]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [61]:
hp_mode = df['horsepower'].mode()[0]
df['horsepower'] = df['horsepower'].fillna(hp_mode)

In [62]:
df['horsepower'].median()

np.float64(252.0)

In [64]:
df_asia = df[df.origin == 'Asia']

In [74]:
df_asia_2 = df_asia[['vehicle_weight', 'model_year']]
df_asia_7 = df_asia_2.head(7)

In [76]:
X = df_asia_7.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [80]:
tr_X = np.transpose(X)

In [94]:
XTX = tr_X.dot(X)
np.linalg.inv(XTX)

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [91]:
lists = [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array(lists) 

In [95]:
w = (np.linalg.inv(XTX).dot(tr_X)).dot(y)
w

array([0.13644777, 0.2327492 ])

In [97]:
w.sum()

np.float64(0.36919696904925486)